spring.application.name=anotacoes

spring.datasource.url=jdbc:postgresql://localhost:5432/db_anotacoes
spring.datasource.username=postgres
spring.datasource.password=Pgminfo1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Para alterar a porta use:
server.port=8081

app.upload.dir=uploads/usuarios/

jwt.secret=sua-chave-secreta-super-segura-que-deve-ser-bem-longa

logging.level.org.springframework.security=DEBUG

